# Generated by Django 5.0.2 on 2024-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsertionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_data_been_inserted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level', models.CharField(choices=[('€', '€'), ('€€-€€€', '€€-€€€'), ('€€€€', '€€€€')], max_length=10)),
                ('vegetarian_friendly', models.BooleanField(default=False)),
                ('vegan_options', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('avg_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10)),
                ('region', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_link', models.TextField()),
                ('restaurant_name', models.TextField()),
                ('original_location', models.TextField()),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('province', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('claimed', models.TextField()),
                ('awards', models.TextField()),
                ('popularity_detailed', models.TextField()),
                ('popularity_generic', models.TextField()),
                ('top_tags', models.TextField()),
                ('price_level', models.TextField()),
                ('price_range', models.TextField()),
                ('meals', models.TextField()),
                ('cuisines', models.TextField()),
                ('special_diets', models.TextField()),
                ('features', models.TextField()),
                ('vegetarian_friendly', models.TextField()),
                ('vegan_options', models.TextField()),
                ('gluten_free', models.TextField()),
                ('original_open_hours', models.TextField()),
                ('open_days_per_week', models.TextField()),
                ('open_hours_per_week', models.TextField()),
                ('working_shifts_per_week', models.TextField()),
                ('avg_rating', models.TextField()),
                ('total_reviews_count', models.TextField()),
                ('default_language', models.TextField()),
                ('reviews_count_in_default_language', models.TextField()),
                ('excellent', models.TextField()),
                ('very_good', models.TextField()),
                ('average', models.TextField()),
                ('poor', models.TextField()),
                ('terrible', models.TextField()),
                ('food', models.TextField()),
                ('service', models.TextField()),
                ('value', models.TextField()),
                ('atmosphere', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
